config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :portfolios
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

 	resources :blogs do
  		member do
  			get :toggle_status
  		end
  	end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: {draft: 0,published:1}
	extend FriendlyId
	friendly_id :title, use: :slugged

	validates_presence_of :title,:body

	#belongs_to :topic
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new,:create,:update,:edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Post criado com sucesso.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Post foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Post foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Post teve status alterado com sucesso.' }
      format.json { head :no_content }
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
    <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
    <p class="blog-post-meta"><%= distance_of_time_in_words(blog.created_at, Time.now) %></p>
    <p class="blog-post-meta"><%= blog.body %></p>
    <% if logged_in?(:site_admin) %>
   		<p class="blog-post-meta">
    		<%= link_to  blog.status, toggle_status_blog_path(blog)%> /
    		<%= link_to  'Editar' , edit_blog_path(blog) %> /
    		<%= link_to 'Deletar Post', blog, method: :delete,  data: { confirm: 'Tem certeza?' } %>
    		</p>
    <% end %>    
    <hr>        
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Título %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Conteúdo %>
    <br>
    <%= form.text_area :body , rows: 10%>
  </div>

    <div class="field">
    <%= form.label :Tópico %>
    <%= form.text_field :topic %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">
	<h1>Editar Post</h1>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Mostrar', @blog %> |
	<%= link_to 'Voltar', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-md-8 blog-main">
          <%= render @blogs%>
</div>

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
	<h1>Novo  Post</h1>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Voltar', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main">
	<h2><%= @blog.title %></h2>
	<%= link_to 'Editar', edit_blog_path(@blog)  if logged_in?(:site_admin)  %>
    <p><%= @blog.body %></p>

</div>