config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :portfolios
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

 	resources :blogs do
  		member do
  			get :toggle_status
  		end
  	end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies, reject_if: lambda {|attrs| attrs['name'].blank?}
	include Placeholder
	validates_presence_of :title,:body


	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

	def self.angular
		where(subtitle: 'Angular')
	end

	after_initialize :set_defaults


	def set_defaults
		self.main_image ||= Placeholder.image_generator(height: '600',width: '250',text:"#{title}")
		self.thumb_image ||= Placeholder.image_generator(height: '350',width: '200',text:"#{title}")
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new,:create,:update,:edit]}, site_admin: :all
	def index
		@portfolio_items = Portfolio.all
	end
	def new
		@portfolio_item = Portfolio.new
    3.times{@portfolio_item.technologies.build}
	end
	def create
  		@portfolio_item = Portfolio.new(portfolio_params)
    	respond_to do |format|
      		if @portfolio_item.save
        		format.html { redirect_to portfolios_path, notice: 'Portfolio criado com sucesso.' }
        		format.json { render :show, status: :created, location: @portfolio }
      		else
        		format.html { render :new }
        		format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      		end
    	end
 	end
 	def edit
 		@portfolio_item = Portfolio.find(params[:id])
 	end
 	def update
 		@portfolio_item = Portfolio.find(params[:id])
    	respond_to do |format|
      		if @portfolio_item.update(portfolio_params)
        		format.html { redirect_to portfolios_path, notice: 'Portfolio foi atualizado com sucesso.' }
        		format.json { render :show, status: :ok, location: @blog }
      		else
        	format.html { render :edit }
        	format.json { render json: @blog.errors, status: :unprocessable_entity }
      		end
    	end
  end
  def show
    @portfolio_item = Portfolio.find(params[:id])
  end
  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio foi apagado com sucesso.' }        
      format.json { head :no_content }
    end
  end
  private
    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle, 
                                        :body,
                                        technologies_attributes:[:name]
                                        )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<H1>Criar novo Portfolio</H1>
<%= form_for(@portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :Título %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Subtitulo %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :Conteúdo %>
    <%= form.text_area :body %>
  </div>
  <ul>
    <%= form.fields_for :technologies do |techology_form| %>
    <li>
      <%= techology_form.label :name %>
      <%= techology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<h3> <%=  link_to portfolio_item.title, portfolio_path(portfolio_item.id) =%> </h3>
<h4> <%= portfolio_item.subtitle =%> <h4>
<p> <%= portfolio_item.body =%> </p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? =%>
<%= link_to "Editar", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) =%>
<%= link_to 'Deletar Item', portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Tem certeza?' } if logged_in?(:site_admin) %>

app/views/portfolios/edit.html.erb
<H1>Editar Portfolio</H1>
<%= form_for(@portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :Título %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Subtitulo %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :Conteúdo %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<H1>Index da pagina de Portfolio</H1>

<%= link_to "Criar novo item Portfolio", new_portfolio_path if logged_in?(:site_admin) %>



<%= render partial:'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<%= render 'form', portfolio_item: @portfolio_item  %>

app/views/portfolios/show.html.erb
<%=  image_tag @portfolio_item.main_image =%>
<h1><%= @portfolio_item.title =%></h1>
<em><%= @portfolio_item.subtitle =%></em>
<p><%= @portfolio_item.body =%></p>

<H2>Tecnologias utilizadas</H2>
<% @portfolio_item.technologies.each do |a| %>
<p><%= a.name %></p>

<% end %>