config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :portfolios
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

 	resources :blogs do
  		member do
  			get :toggle_status
  		end
  	end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
     <div class="inner">
       <p><%= @copyright %></p>
     </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Jonatas da Luz</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to "Paginal inicial", root_path, class: 'nav-link' %>
      <%= link_to "Sobre", about_path, class: 'nav-link' %>
      <%= link_to "Contato", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="mastfoot mt-auto">
     <div class="inner">
       <p><%= @copyright %></p>
     </div>
</footer>

app/views/shared/_blog_nav.html.erb
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <h2 class="blog-header-logo text-dark" >Jonatas da Luz</h2>
      <%= link_to "Paginal inicial", root_path, class: 'p-2 text-muted' %>
      <%= link_to "Sobre", about_path, class: 'p-2 text-muted' %>
      <%= link_to "Contato", contact_path, class: 'p-2 text-muted' %>
      <%= link_to "Blog", blogs_path, class: 'p-2 text-muted' %>
      <%= login_helper 'p-2 text-muted' %>
    </nav>
  </div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">Sobre mim</h4>
    <p class="mb-0">Nasci e moro em Curitiba, PR. Estudante de Bacharelado em Sistemas de Informação na Universidade Tecnológica Federal do Paraná.
      Atualmente trabalho como Analista de Sistemas na empresa Plansul - Planejamento e Consultoria, desenvolvendo ferramentas em PHP para gestão de processos do Call Center voltado para registro de reclamações e denúncias de operadoras de telecomunicações da Anatel.
      Apaixonado por música, mesmo sem saber tocar nenhum instrumento. No meu tempo livre gosto jogar videogames, participar de RPGs e board games.
    </p>
  </div>
   </aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
<div><%= link_to "Paginal inicial", root_path %></div>
<div><%= link_to "Sobre", about_path %></div>
<div><%= link_to "Contato", contact_path %></div>
<div><%= link_to "Blog", blogs_path %></div>
<div><%= link_to "Portfolio", portfolios_path %></div>

</div>