config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :portfolios
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

 	resources :blogs do
  		member do
  			get :toggle_status
  		end
  	end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <%= render "shared/application_nav"%>
      <main role="main" class="inner cover">
      
      </main>

      <%= yield %>
      <%= source_helper("application") %>
      <%= render "shared/application_footer" %>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render 'shared/blog_nav' %>
      

      <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic"><%= Blog.last.title %></h1>
          <p class="lead my-3"><%= truncate(Blog.last.body, :length => 150)  %></p>
          <p class="lead mb-0"><a href="../../blogs/<%=a= Blog.last.slug %>" class="text-white font-weight-bold">Continue lendo...</a></p>
        </div>
      </div>

     <%= link_to 'Novo Post', new_blog_path if logged_in?(:site_admin) %>
    <div class="container">
      <div class ="row">
        <%= yield %>
        <%= render 'shared/blog_sidebar' %>
        <%= source_helper("blog") %>

        <%= render 'shared/blog_footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/nav", location: 'top' ;%>
    <%= login_helper 'nav-link' %>


    <%= yield %>
    <%= source_helper("portfolio") %>

  </body>
</html>